import React from "react";
import {
  // --- UI & General ---
  HiQuestionMarkCircle,
  HiEllipsisHorizontalCircle,
  HiCheckCircle,
  HiXCircle,
  HiFlag,

  // --- Home & Living ---
  HiHome,
  HiHomeModern,
  HiSparkles,
  HiArchiveBox,
  HiKey,
  HiBolt,
  HiFire,
  HiCloud,
  HiBuildingOffice,
  HiSwatch,

  // --- Services ---
  HiClipboardDocumentList,
  HiInbox,
  HiScale,

  // --- Communication ---
  HiWifi,
  HiDevicePhoneMobile,
  HiGlobeAlt,

  // --- Food ---
  HiShoppingCart,
  HiShoppingBag,
  HiBuildingStorefront,
  HiCake,
  HiBeaker,
  HiNoSymbol,

  // --- Transport ---
  HiTruck,
  HiMapPin,
  HiMap,
  HiTicket,
  HiFunnel,
  HiWrenchScrewdriver,
  HiWrench,
  HiShieldCheck,
  HiExclamationCircle,

  // --- Travel ---
  HiGlobeAmericas,
  HiPaperAirplane,
  HiBriefcase,

  // --- Shopping ---
  HiTag,
  HiDeviceTablet,
  HiComputerDesktop,
  HiFaceSmile,
  HiGift,

  // --- Health ---
  HiHeart,
  HiPlusCircle,
  HiUser,
  HiUserGroup,

  // --- Education ---
  HiAcademicCap,
  HiBookOpen,
  HiPresentationChartLine,
  HiChatBubbleLeftRight,
  HiCodeBracket,

  // --- Entertainment ---
  HiFilm,
  HiTrophy,
  HiPlay,
  HiMusicalNote,
  HiPuzzlePiece,

  // --- Finance & Obligations ---
  HiBanknotes,
  HiHandRaised,
  HiUsers,
  HiDocumentText,
  HiReceiptPercent,
  HiExclamationTriangle,
  HiChartBar,
  HiSun,
  HiCube,
  HiStar,
  HiCurrencyDollar,
  HiTrash,
  HiArrowTrendingDown,
  HiArrowTrendingUp,
  HiArrowsRightLeft,
  HiCreditCard,
  HiCircleStack,
  HiBell,
  HiBuildingLibrary,
  HiCalculator,
  HiCalendarDays,
  HiCamera,
  HiChartPie,
  HiClock,
  HiCog6Tooth,
  HiDocumentCurrencyDollar,
  HiEnvelope,
  HiFolder,
  HiFolderOpen,
  HiLightBulb,
  HiLockClosed,
  HiMagnifyingGlass,
  HiMoon,
  HiNewspaper,
  HiPaintBrush,
  HiPencilSquare,
  HiPhone,
  HiPhoto,
  HiReceiptRefund,
  HiRocketLaunch,
  HiScissors,
  HiSpeakerWave,
  HiLanguage,
} from "react-icons/hi2";

// === 1. МАПА ІКОНОК ===
export const ICON_MAP: Record<string, React.ElementType> = {
  HiEllipsisHorizontalCircle,
  HiQuestionMarkCircle,
  HiCheckCircle,
  HiXCircle,
  HiHome,
  HiHomeModern,
  HiShoppingCart,
  HiBuildingStorefront,
  HiClipboardDocumentList,
  HiGlobeAmericas,
  HiScale,
  HiBanknotes,
  HiBriefcase,
  HiAcademicCap,
  HiHeart,
  HiTicket,
  HiShoppingBag,
  HiWifi,
  HiKey,
  HiMapPin,
  HiInbox,
  HiTag,
  HiSparkles,
  HiArchiveBox,
  HiSwatch,
  HiBolt,
  HiFire,
  HiCloud,
  HiBuildingOffice,
  HiDevicePhoneMobile,
  HiGlobeAlt,
  HiPlay,
  HiCake,
  HiBeaker,
  HiNoSymbol,
  HiTruck,
  HiMap,
  HiFunnel,
  HiWrenchScrewdriver,
  HiWrench,
  HiShieldCheck,
  HiExclamationCircle,
  HiPaperAirplane,
  HiDeviceTablet,
  HiComputerDesktop,
  HiFaceSmile,
  HiGift,
  HiPlusCircle,
  HiUser,
  HiUserGroup,
  HiBookOpen,
  HiPresentationChartLine,
  HiChatBubbleLeftRight,
  HiCodeBracket,
  HiFilm,
  HiTrophy,
  HiMusicalNote,
  HiPuzzlePiece,
  HiHandRaised,
  HiUsers,
  HiDocumentText,
  HiReceiptPercent,
  HiExclamationTriangle,
  HiChartBar,
  HiSun,
  HiCube,
  HiStar,
  HiCurrencyDollar,
  HiTrash,
  HiArrowTrendingDown,
  HiArrowTrendingUp,
  HiArrowsRightLeft,
  HiCreditCard,
  HiCircleStack,
  HiFlag,
  HiBell,
  HiBuildingLibrary,
  HiCalculator,
  HiCalendarDays,
  HiCamera,
  HiChartPie,
  HiClock,
  HiCog6Tooth,
  HiDocumentCurrencyDollar,
  HiEnvelope,
  HiFolder,
  HiFolderOpen,
  HiLightBulb,
  HiLockClosed,
  HiMagnifyingGlass,
  HiMoon,
  HiNewspaper,
  HiPaintBrush,
  HiPencilSquare,
  HiPhone,
  HiPhoto,
  HiReceiptRefund,
  HiRocketLaunch,
  HiScissors,
  HiSpeakerWave,
  HiLanguage,
};

// Набір для picker-а. Це не окрема мапа: кожна іконка тут гарантовано
// підтримується CategoryIcon і в усіх списках застосунку відображається однаково.
export const PICKER_ICON_NAMES = [
  "HiShoppingBag", "HiShoppingCart", "HiBuildingStorefront", "HiTag",
  "HiHome", "HiHomeModern", "HiBuildingOffice", "HiBuildingLibrary",
  "HiBanknotes", "HiCreditCard", "HiCurrencyDollar", "HiReceiptPercent",
  "HiCalculator", "HiChartBar", "HiChartPie", "HiBriefcase",
  "HiTruck", "HiMapPin", "HiMap", "HiTicket", "HiWrench", "HiKey",
  "HiBolt", "HiLightBulb", "HiFire", "HiCloud", "HiWifi", "HiPhone",
  "HiComputerDesktop", "HiDevicePhoneMobile", "HiDeviceTablet", "HiCamera",
  "HiHeart", "HiAcademicCap", "HiBookOpen", "HiUser", "HiUsers",
  "HiGlobeAlt", "HiGlobeAmericas", "HiCalendarDays", "HiClock",
  "HiGift", "HiCake", "HiStar", "HiSun", "HiMoon", "HiSparkles",
  "HiFilm", "HiMusicalNote", "HiPuzzlePiece", "HiFaceSmile",
  "HiFolder", "HiDocumentText", "HiNewspaper", "HiPhoto", "HiPaintBrush",
  "HiBell", "HiEnvelope", "HiMagnifyingGlass", "HiCog6Tooth", "HiLockClosed",
  "HiRocketLaunch", "HiFlag", "HiShieldCheck", "HiHandRaised",
] as const;
