import React from "react";
import {
  // --- UI & General ---
  HiQuestionMarkCircle,
  HiEllipsisHorizontalCircle,
  HiCheckCircle,
  HiXCircle,
  HiFlag,

  // --- Home & Living ---
  HiHome,
  HiHomeModern,
  HiSparkles,
  HiArchiveBox,
  HiKey,
  HiBolt,
  HiFire,
  HiCloud,
  HiBuildingOffice,
  HiSwatch,

  // --- Services ---
  HiClipboardDocumentList,
  HiInbox,
  HiScale,

  // --- Communication ---
  HiWifi,
  HiDevicePhoneMobile,
  HiGlobeAlt,

  // --- Food ---
  HiShoppingCart,
  HiShoppingBag,
  HiBuildingStorefront,
  HiCake,
  HiBeaker,
  HiNoSymbol,

  // --- Transport ---
  HiTruck,
  HiMapPin,
  HiMap,
  HiTicket,
  HiFunnel,
  HiWrenchScrewdriver,
  HiWrench,
  HiShieldCheck,
  HiExclamationCircle,

  // --- Travel ---
  HiGlobeAmericas,
  HiPaperAirplane,
  HiBriefcase,

  // --- Shopping ---
  HiTag,
  HiDeviceTablet,
  HiComputerDesktop,
  HiFaceSmile,
  HiGift,

  // --- Health ---
  HiHeart,
  HiPlusCircle,
  HiUser,
  HiUserGroup,

  // --- Education ---
  HiAcademicCap,
  HiBookOpen,
  HiPresentationChartLine,
  HiChatBubbleLeftRight,
  HiCodeBracket,

  // --- Entertainment ---
  HiFilm,
  HiTrophy,
  HiPlay,
  HiMusicalNote,
  HiPuzzlePiece,

  // --- Finance & Obligations ---
  HiBanknotes,
  HiHandRaised,
  HiUsers,
  HiDocumentText,
  HiReceiptPercent,
  HiExclamationTriangle,
  HiChartBar,
  HiSun,
  HiCube,
  HiStar,
  HiCurrencyDollar,
  HiTrash,
  HiArrowTrendingDown,
  HiArrowTrendingUp,
  HiArrowsRightLeft,
  HiCreditCard,
  HiCircleStack,
  HiBell,
  HiBuildingLibrary,
  HiCalculator,
  HiCalendarDays,
  HiCamera,
  HiChartPie,
  HiClock,
  HiCog6Tooth,
  HiDocumentCurrencyDollar,
  HiEnvelope,
  HiFolder,
  HiFolderOpen,
  HiLightBulb,
  HiLockClosed,
  HiMagnifyingGlass,
  HiMoon,
  HiNewspaper,
  HiPaintBrush,
  HiPencilSquare,
  HiPhone,
  HiPhoto,
  HiReceiptRefund,
  HiRocketLaunch,
  HiScissors,
  HiSpeakerWave,
  HiLanguage,
  HiEllipsisHorizontal,
  HiEllipsisVertical,
  HiWallet,
  HiBuildingOffice2,
  HiCalendar,
  HiClipboard,
  HiDocumentDuplicate,
  HiEye,
  HiLink,
  HiListBullet,
  HiMegaphone,
  HiMicrophone,
  HiPaperClip,
  HiPrinter,
  HiQrCode,
  HiRadio,
  HiShare,
  HiTableCells,
  HiTv,
  HiVideoCamera,
  HiBookmark,
  HiCheckBadge,
  HiHandThumbUp,
  HiHandThumbDown,
  HiFingerPrint,
  HiCpuChip,
} from "react-icons/hi2";
import {
  Baby,
  Bed,
  Bike,
  Bird,
  Bone,
  Bus,
  Car,
  Cat,
  Coffee,
  Dog,
  Dumbbell,
  Fish,
  Gamepad2,
  GraduationCap,
  PawPrint,
  Plane,
  Rabbit,
  Salad,
  Shirt,
  Stethoscope,
  Utensils,
} from "lucide-react";

// === 1. МАПА ІКОНОК ===
export const ICON_MAP: Record<string, React.ElementType> = {
  HiEllipsisHorizontalCircle,
  HiQuestionMarkCircle,
  HiCheckCircle,
  HiXCircle,
  HiHome,
  HiHomeModern,
  HiShoppingCart,
  HiBuildingStorefront,
  HiClipboardDocumentList,
  HiGlobeAmericas,
  HiScale,
  HiBanknotes,
  HiBriefcase,
  HiAcademicCap,
  HiHeart,
  HiTicket,
  HiShoppingBag,
  HiWifi,
  HiKey,
  HiMapPin,
  HiInbox,
  HiTag,
  HiSparkles,
  HiArchiveBox,
  HiSwatch,
  HiBolt,
  HiFire,
  HiCloud,
  HiBuildingOffice,
  HiDevicePhoneMobile,
  HiGlobeAlt,
  HiPlay,
  HiCake,
  HiBeaker,
  HiNoSymbol,
  HiTruck,
  HiMap,
  HiFunnel,
  HiWrenchScrewdriver,
  HiWrench,
  HiShieldCheck,
  HiExclamationCircle,
  HiPaperAirplane,
  HiDeviceTablet,
  HiComputerDesktop,
  HiFaceSmile,
  HiGift,
  HiPlusCircle,
  HiUser,
  HiUserGroup,
  HiBookOpen,
  HiPresentationChartLine,
  HiChatBubbleLeftRight,
  HiCodeBracket,
  HiFilm,
  HiTrophy,
  HiMusicalNote,
  HiPuzzlePiece,
  HiHandRaised,
  HiUsers,
  HiDocumentText,
  HiReceiptPercent,
  HiExclamationTriangle,
  HiChartBar,
  HiSun,
  HiCube,
  HiStar,
  HiCurrencyDollar,
  HiTrash,
  HiArrowTrendingDown,
  HiArrowTrendingUp,
  HiArrowsRightLeft,
  HiCreditCard,
  HiCircleStack,
  HiFlag,
  HiBell,
  HiBuildingLibrary,
  HiCalculator,
  HiCalendarDays,
  HiCamera,
  HiChartPie,
  HiClock,
  HiCog6Tooth,
  HiDocumentCurrencyDollar,
  HiEnvelope,
  HiFolder,
  HiFolderOpen,
  HiLightBulb,
  HiLockClosed,
  HiMagnifyingGlass,
  HiMoon,
  HiNewspaper,
  HiPaintBrush,
  HiPencilSquare,
  HiPhone,
  HiPhoto,
  HiReceiptRefund,
  HiRocketLaunch,
  HiScissors,
  HiSpeakerWave,
  HiLanguage,
  HiEllipsisHorizontal,
  HiEllipsisVertical,
  HiWallet,
  HiBuildingOffice2,
  HiCalendar,
  HiClipboard,
  HiDocumentDuplicate,
  HiEye,
  HiLink,
  HiListBullet,
  HiMegaphone,
  HiMicrophone,
  HiPaperClip,
  HiPrinter,
  HiQrCode,
  HiRadio,
  HiShare,
  HiTableCells,
  HiTv,
  HiVideoCamera,
  HiBookmark,
  HiCheckBadge,
  HiHandThumbUp,
  HiHandThumbDown,
  HiFingerPrint,
  HiCpuChip,
  LuPawPrint: PawPrint,
  LuCat: Cat,
  LuDog: Dog,
  LuRabbit: Rabbit,
  LuBird: Bird,
  LuFish: Fish,
  LuBone: Bone,
  LuCar: Car,
  LuBus: Bus,
  LuBike: Bike,
  LuPlane: Plane,
  LuUtensils: Utensils,
  LuCoffee: Coffee,
  LuSalad: Salad,
  LuStethoscope: Stethoscope,
  LuDumbbell: Dumbbell,
  LuGamepad2: Gamepad2,
  LuBaby: Baby,
  LuShirt: Shirt,
  LuBed: Bed,
  LuGraduationCap: GraduationCap,
};

// Набір для picker-а. Це не окрема мапа: кожна іконка тут гарантовано
// підтримується CategoryIcon і в усіх списках застосунку відображається однаково.
export const PICKER_ICON_NAMES = [
  // General & "Other"
  "HiEllipsisHorizontalCircle", "HiEllipsisHorizontal", "HiEllipsisVertical",
  "HiQuestionMarkCircle", "HiTag", "HiBookmark", "HiFolder", "HiFolderOpen",
  "HiListBullet", "HiClipboard", "HiDocumentText", "HiDocumentDuplicate",
  // Pets & family
  "LuPawPrint", "LuCat", "LuDog", "LuRabbit", "LuBird", "LuFish", "LuBone",
  "HiUser", "HiUsers", "HiUserGroup", "LuBaby",
  // Food, home & everyday
  "HiShoppingBag", "HiShoppingCart", "HiBuildingStorefront", "HiTag",
  "HiHome", "HiHomeModern", "HiBuildingOffice", "HiBuildingLibrary",
  "LuUtensils", "LuCoffee", "LuSalad", "HiCake", "LuShirt", "LuBed",
  // Money & work
  "HiBanknotes", "HiCreditCard", "HiCurrencyDollar", "HiReceiptPercent",
  "HiCalculator", "HiChartBar", "HiChartPie", "HiBriefcase", "HiWallet",
  "HiBuildingOffice2", "HiCheckBadge", "HiFingerPrint",
  // Transport & travel
  "HiTruck", "HiMapPin", "HiMap", "HiTicket", "HiWrench", "HiKey",
  "LuCar", "LuBus", "LuBike", "LuPlane",
  // Utilities & technology
  "HiBolt", "HiLightBulb", "HiFire", "HiCloud", "HiWifi", "HiPhone",
  "HiComputerDesktop", "HiDevicePhoneMobile", "HiDeviceTablet", "HiCamera",
  "HiCpuChip", "HiTv", "HiVideoCamera", "HiRadio", "HiMicrophone", "HiPrinter", "HiQrCode",
  // Health, learning & leisure
  "HiHeart", "LuStethoscope", "LuDumbbell", "HiAcademicCap", "LuGraduationCap", "HiBookOpen",
  "HiGlobeAlt", "HiGlobeAmericas", "HiCalendarDays", "HiCalendar", "HiClock",
  "HiGift", "HiCake", "HiStar", "HiSun", "HiMoon", "HiSparkles",
  "HiFilm", "HiMusicalNote", "HiPuzzlePiece", "LuGamepad2", "HiFaceSmile",
  // Communication & actions
  "HiNewspaper", "HiPhoto", "HiPaintBrush", "HiBell", "HiEnvelope", "HiMegaphone",
  "HiMagnifyingGlass", "HiEye", "HiLink", "HiPaperClip", "HiShare", "HiCog6Tooth",
  "HiLockClosed", "HiRocketLaunch", "HiFlag", "HiShieldCheck", "HiHandRaised",
  "HiHandThumbUp", "HiHandThumbDown",
] as const;
